# Generated by Django 4.1.3 on 2022-12-17 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_order_orderproduct_order_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='qty',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество'),
        ),
    ]
