# Generated by Django 4.1.3 on 2023-01-11 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_cart_qty'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
